FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /workspace/halfweg

RUN pip install --no-cache-dir pyyaml numba tensorboard

CMD ["python", "src/go_halfweg.py", "configs/evaluate_boxoban_unfiltered_test_000_gpu.yaml"]
